# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: ido_development
  username: thiagoMB
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: ido_test
  username: thiagoMB
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: ido_production
